name: SonarQube Analysis

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Python version
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'  # Replace with your project's Python version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests (optional)
        run: pytest  # Replace with your test command

      - name: Analyze with SonarQube
        uses: sonarsource/sonarcloud-github-action@master  # Replace with community action for self-hosted SonarQube
        with:
          projectKey: python
          organization: ${{ secrets.SONAR_ORGANIZATION }}  # Optional for SonarCloud
          token: ${{ secrets.SONAR_SCANNER_TOKEN }}
          # (Optional) coverageReportFile: coverage.xml  # Path to your coverage report
