name: SonarQube Analysis

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Python version
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'  # Replace with your project's Python version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Analyze with SonarQube
        uses: sonarsource/sonarqube-scan-action@master  # Replace with community action for self-hosted SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: .
